# Generated by Django 5.1.7 on 2025-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='Videos')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
